name: Build and Commit Scripting App

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Build Scripting App
        run: npm run build
      
      - name: Commit and push dist directory
        run: |
          git add dist/
          git diff --cached --quiet --exit-code || (
            git commit -m "Auto-update: Build scripts at $(Get-Date -Format o)" &&
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:dev
          )
        shell: pwsh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scripting-apps
          path: dist/*.scripting
